# Generated by Django 4.2 on 2023-04-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("Set_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Patient_ID", models.CharField(max_length=50)),
                (
                    "Patient_Identifier_List",
                    models.CharField(blank=True, max_length=200),
                ),
                ("Alternate_Patient_ID", models.CharField(blank=True, max_length=50)),
                ("Patient_Name", models.CharField(max_length=100)),
                ("Mother_Maiden_Name", models.CharField(blank=True, max_length=100)),
                ("Date_of_Birth", models.DateField()),
                (
                    "Sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("Patient_Alias", models.CharField(blank=True, max_length=30)),
                ("Race", models.CharField(blank=True, max_length=50)),
                ("Patient_Address", models.CharField(max_length=200)),
                ("County_Code", models.CharField(blank=True, max_length=5)),
                ("Phone_Number_Home", models.CharField(blank=True, max_length=20)),
                ("Phone_Number_Business", models.CharField(blank=True, max_length=20)),
                ("Primary_Language", models.CharField(blank=True, max_length=50)),
                ("Marital_Status", models.CharField(blank=True, max_length=20)),
                ("Religion", models.CharField(blank=True, max_length=50)),
                ("Patient_Account_Number", models.CharField(blank=True, max_length=50)),
                ("SSN_Number_Patient", models.CharField(blank=True, max_length=9)),
                ("Driver_License_Number", models.CharField(blank=True, max_length=20)),
                ("Mother_Identier", models.CharField(blank=True, max_length=30)),
                ("Ethnic_Group", models.CharField(blank=True, max_length=50)),
                (
                    "Birth_Place",
                    models.CharField(blank=True, default="unknown", max_length=50),
                ),
                ("Multiple_Birth_Indicator", models.BooleanField()),
                ("Birth_Order", models.PositiveIntegerField(blank=True, null=True)),
                ("Citizenship", models.CharField(blank=True, max_length=50)),
                (
                    "Veterans_Military_Status",
                    models.CharField(blank=True, max_length=50),
                ),
                ("Nationality_Code", models.CharField(blank=True, max_length=5)),
                (
                    "PatientDeath_Date_and_Time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("Patient_Death_Indicator", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                ("Set_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Specimen_ID", models.CharField(max_length=50)),
                ("Specimen_Parent_ID", models.CharField(blank=True, max_length=50)),
                ("Specimen_Type", models.CharField(max_length=50)),
                ("Specimen_Type_Modifier", models.CharField(blank=True, max_length=50)),
                ("Specimen_Additives", models.CharField(blank=True, max_length=50)),
                (
                    "Specimen_Collection_Method",
                    models.CharField(blank=True, max_length=50),
                ),
                ("Specimen_SourceSite", models.CharField(blank=True, max_length=50)),
                (
                    "Specimen_Source_Site_Modifier",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "Specimen_Collection_Site",
                    models.CharField(blank=True, max_length=50),
                ),
                ("Specimen_Role", models.CharField(blank=True, max_length=50)),
                (
                    "Specimen_Collection_Amount",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "Grouped_Specimen_Count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("Specimen_Description", models.CharField(blank=True, max_length=200)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimens",
                        to="lis_app.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Order_control", models.CharField(max_length=2)),
                ("Placer_order_number", models.CharField(max_length=22)),
                ("Filler_order_number", models.CharField(blank=True, max_length=22)),
                ("Placer_group_number", models.CharField(blank=True, max_length=22)),
                ("Order_status", models.CharField(max_length=2)),
                ("Response_flag", models.CharField(blank=True, max_length=1)),
                ("Quantity_timing", models.CharField(blank=True, max_length=200)),
                ("Parent", models.CharField(blank=True, max_length=22)),
                ("Date_time_transaction", models.DateTimeField()),
                ("Entered_by", models.CharField(max_length=60)),
                ("Verified_by", models.CharField(blank=True, max_length=60)),
                ("Ordering_provider", models.CharField(blank=True, max_length=120)),
                ("Enterers_location", models.CharField(blank=True, max_length=60)),
                ("Call_back_phone_number", models.CharField(blank=True, max_length=40)),
                (
                    "Order_effective_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "Order_control_code_reason",
                    models.CharField(blank=True, max_length=200),
                ),
                ("Entering_organization", models.CharField(blank=True, max_length=200)),
                ("Entering_device", models.CharField(blank=True, max_length=200)),
                ("Action_by", models.CharField(blank=True, max_length=120)),
                (
                    "Advanced_beneficiary_notice_code",
                    models.CharField(blank=True, max_length=2),
                ),
                (
                    "Ordering_facility_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "Ordering_facility_address",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "Ordering_facility_phone_number",
                    models.CharField(blank=True, max_length=40),
                ),
                (
                    "Ordering_provider_address",
                    models.CharField(blank=True, max_length=200),
                ),
                ("Order_status_modifier", models.CharField(blank=True, max_length=1)),
                (
                    "Advanced_beneficiary_notice_override_reason",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "Fillers_expected_availability_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("Confidentiality_code", models.CharField(blank=True, max_length=4)),
                ("Order_type", models.CharField(blank=True, max_length=2)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="lis_app.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("Set_id", models.IntegerField(primary_key=True, serialize=False)),
                ("Value_type", models.CharField(max_length=2)),
                ("Observation_identifier", models.CharField(max_length=250)),
                ("Observation_sub_id", models.CharField(max_length=20)),
                ("Observation_value", models.CharField(max_length=250)),
                ("Units", models.CharField(max_length=20)),
                ("Reference_range", models.CharField(max_length=250)),
                ("Abnormal_flags", models.CharField(max_length=5)),
                ("Probability", models.DecimalField(decimal_places=2, max_digits=4)),
                ("Nature_of_abnormal_test", models.CharField(max_length=250)),
                ("Observation_result_status", models.CharField(max_length=1)),
                ("Effective_date_of_reference_range", models.DateField()),
                ("User_defined_access_checks", models.CharField(max_length=20)),
                ("Observation_date_time", models.DateTimeField()),
                ("Producers_id", models.CharField(max_length=250)),
                ("Responsible_observer", models.CharField(max_length=250)),
                ("Observation_method", models.CharField(max_length=250)),
                ("Equipment_instance_identifier", models.CharField(max_length=250)),
                ("Analysis_date_time", models.DateTimeField()),
                ("Observation_site", models.CharField(max_length=250)),
                ("Observation_instance_identifier", models.CharField(max_length=250)),
                ("Mood_code", models.CharField(max_length=3)),
                ("Performing_organization_name", models.CharField(max_length=250)),
                ("Performing_organization_address", models.CharField(max_length=250)),
                (
                    "Performing_organization_medical_director",
                    models.CharField(max_length=250),
                ),
                ("Patient_results_release_category", models.CharField(max_length=20)),
                ("Root_cause_of_delay", models.CharField(max_length=250)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="lis_app.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message_headers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sending_application", models.CharField(max_length=255)),
                ("sending_facility", models.CharField(max_length=255)),
                ("receiving_application", models.CharField(max_length=255)),
                ("receiving_facility", models.CharField(max_length=255)),
                ("date_time_of_message", models.DateTimeField()),
                ("security", models.CharField(max_length=255)),
                ("message_type", models.CharField(max_length=255)),
                ("message_control_id", models.CharField(max_length=255)),
                ("processing_id", models.CharField(max_length=255)),
                ("version_id", models.CharField(max_length=255)),
                ("sequence_number", models.IntegerField()),
                ("continuation_pointer", models.CharField(max_length=255)),
                ("accept_acknowledgment_type", models.CharField(max_length=255)),
                ("application_acknowledgment_type", models.CharField(max_length=255)),
                ("country_code", models.CharField(max_length=255)),
                ("character_set", models.CharField(max_length=255)),
                ("principal_language_of_message", models.CharField(max_length=255)),
                (
                    "alternate_character_set_handling_scheme",
                    models.CharField(max_length=255),
                ),
                ("message_profile_identifier", models.CharField(max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messagesHeaders",
                        to="lis_app.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                ("set_id", models.IntegerField(primary_key=True, serialize=False)),
                ("Placer_order_number", models.CharField(max_length=50)),
                ("Filler_order_number", models.CharField(max_length=50)),
                ("Universal_service_identifier", models.CharField(max_length=50)),
                ("Priority", models.CharField(blank=True, max_length=50)),
                ("Requested_ordered_date_time", models.DateTimeField()),
                ("Observation_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "Observation_end_date_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("Collection_volume", models.CharField(blank=True, max_length=50)),
                ("Collector_identifier", models.CharField(blank=True, max_length=50)),
                ("Specimen_action_code", models.CharField(blank=True, max_length=50)),
                ("Dnger_code", models.CharField(blank=True, max_length=50)),
                (
                    "Relevant_clinical_information",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "Specimen_received_date_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("Specimen_source", models.CharField(blank=True, max_length=50)),
                ("Ordering_provider", models.CharField(blank=True, max_length=50)),
                (
                    "Order_callback_phone_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("Placer_field_1", models.CharField(blank=True, max_length=50)),
                ("Placer_field_2", models.CharField(blank=True, max_length=50)),
                ("Filler_field_1", models.CharField(blank=True, max_length=50)),
                ("Filler_field_2", models.CharField(blank=True, max_length=50)),
                (
                    "Results_rpt_status_change_date_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("Charge_to_practice", models.CharField(blank=True, max_length=50)),
                (
                    "Diagnostic_serv_sect_id",
                    models.CharField(blank=True, max_length=50),
                ),
                ("Result_status", models.CharField(blank=True, max_length=50)),
                ("Parent_result", models.CharField(blank=True, max_length=50)),
                ("Quantity_timing", models.CharField(blank=True, max_length=50)),
                ("Result_copies_to", models.CharField(blank=True, max_length=50)),
                ("Parent", models.CharField(blank=True, max_length=50)),
                ("Transportation_mode", models.CharField(blank=True, max_length=50)),
                ("Reason_for_study", models.CharField(blank=True, max_length=200)),
                (
                    "Principal_result_interpreter",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "Assistant_result_interpreter",
                    models.CharField(blank=True, max_length=50),
                ),
                ("Technician", models.CharField(blank=True, max_length=50)),
                ("Transcriptionist", models.CharField(blank=True, max_length=50)),
                ("Scheduled_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "Number_of_sample_containers",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Transport_logistics_of_collected_sample",
                    models.CharField(blank=True, max_length=200),
                ),
                ("Collectors_comment", models.CharField(blank=True, max_length=200)),
                (
                    "Transport_arrangement_responsibility",
                    models.CharField(blank=True, max_length=50),
                ),
                ("Transport_arranged", models.CharField(blank=True, max_length=50)),
                ("Escort_required", models.CharField(blank=True, max_length=50)),
                (
                    "Planned_patient_transport_comment",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laborders",
                        to="lis_app.patient",
                    ),
                ),
            ],
        ),
    ]
