# Generated by Django 4.2 on 2023-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lis_app", "0002_alter_patient_marital_status_dispense"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("serial_number", models.CharField(max_length=50)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("HL7", "HL7"), ("ASTM", "ASTM")], max_length=10
                    ),
                ),
                ("port", models.CharField(max_length=10)),
                (
                    "communication_direction",
                    models.CharField(
                        choices=[
                            ("unidirectional", "Unidirectional"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(max_length=50)),
            ],
        ),
    ]
